chore: Print verification errors in several lines
From:

```
Error: Policy registry://ghcr.io/kubewarden/tests/pod-privileged:v0.1.9 cannot be validated: Image verification failed: missing signatures
```

To:

```
Error: Policy registry://ghcr.io/kubewarden/tests/pod-privileged:v0.1.9 cannot be validated
Image verification failed: missing signatures
```